config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

pybo/urls.py
from django.urls import path
from . import views
from . import chat
from . import get_list
from . import api

app_name='pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('server/', chat.server),
    path('client/', chat.client),
    path('channels/', chat.channels),
    path('channels/<str:room_name>/', chat.room, name='room'),
    path('call_api/', get_list.index),
    path('terminalData/', api.terminal_info, name='terminal_info'),
    path('trainData/', api.train_info, name='train_info'),
]

pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/views.py
# Create your views here.
import pprint

from django.contrib.sites import requests
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer
from .form import QuestionForm
import requests

import time
from socket import *
import threading

def index(request):
    '''
    return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")
    '''

    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)

    '''return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")'''


def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    answer.save()
    return redirect('pybo:detail', question_id=question_id)

def question_created(request):
    " 질문등록 "
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            "form에서 넘어온 값을 임시저장 False - create_date 값이 없어 db저장에 오류가 발생"
            question = form.save(commit=False)
            "create_date 값을 저장당시 시간으로 저장"
            question.create_date = timezone.now()
            "실제 db에 저장"
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
        context = {'form' :form}
        return render(request, 'pybo/question_form.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question ,id=question_id)
    context = {'question' :question}
    return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    url = f'https://www.googleapis.com/geolocation/v1/geolocate?key=AIzaSyCH5HHuysBCaw-kMd_SjSxCFM9un3Kun0Y'
    data = {
        'considerIp': True,
    }
    result = requests.post(url, data=data)
    return HttpResponse(result)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/call/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>버스정보 API</title>
</head>
<body>
<div class="selectArea">
    <label>출발지</label>
    <select id="StartingSelectBox" class="selectBox" name="StartingSelectBox">
      <option value="NAEK010">서울</option>
      <option value="1">대전</option>
      <option value="2">대구</option>
    </select>

    <label>도착지</label>
    <select id="destinationSelectBox" class="selectBox" name="destinationSelectBox">
      <option value="NAEK300">대전</option>
      <option value="1">부산</option>
      <option value="2">진주</option>
    </select>

    <button class="btn" onclick="location.href='{% url 'pybo:terminal_info' %}'">bus!!!!</button>
    <button class="btn" onclick="location.href='{% url 'pybo:train_info' %}'">train!!!!</button>
</div>



</body>

templates/chat/chat_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">What chat room would you like to enter?</h2>
    <input id="room-name-input" type="text" size="100"/><br/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>
</div>



{% endblock %}

templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/pybo/channels/' + roomName + '/';
        };
    </script>
</body>
</html>

templates/chat/my_position.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/chat/room.html
{% extends 'base.html' %}
{% block content %}

<body>
    <div id="body">
        <div id="chat-log" class="main" width="100px" border="1">
            <div style="text-align:center">반갑습니다! 무엇이든 물어보세요!</div>
        </div><br/>
        <input id="chat-message-input" type="text" size="50"/>
        <input id="chat-message-submit" type="button" value="전송"/>
    </div>
</body>

<style>
    #body{}
    .main{
        border:1px; width:600px; height:500px;overflow-y:scroll; background-color:#fbed97;
       }
    .question{text-align:left;margin-left:10px;margin-top:10px}
    .answer{text-align:right;margin-right:30px;margin-top:10px}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/pybo/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        var answer = data['answer'];
        var set_text = '<div class="question">'+message+'</div>';
        set_text += '<div cols="100" rows="20" class="answer">'+answer+'</div>';
        $("#chat-log").append(set_text);
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>



{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>index</th>
            <th>제목</th>
            <th>담당</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>*</td>
            <td><a href="/pybo/server/">Server chat</a></td>
            <td>서버</td>
        </tr>
        <tr>
            <td>*</td>
            <td><a href="/pybo/client/">Client chat</a></td>
            <td>클라이언트</td>
        </tr>
        <tr>
            <td>*</td>
            <td><a href="/pybo/channels/">Channels</a></td>
            <td>강희영</td>
        </tr>
        <tr>
            <td>*</td>
            <td><a href="/pybo/call_api/">API 호출22</a></td>
            <td>이동희</td>
        </tr>
        </tbody>
    </table>
<!--    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>-->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">내 위치 찾기</a>
</div>

{% endblock %}